backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
          - "!CLAUDE.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/src/test/**"
          - "frontend/src/**/*.test.*"
          - "frontend/e2e/**"
