package com.retra.shared.domain

enum class ErrorCode(val code: String) {
    // Common
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    BAD_REQUEST("BAD_REQUEST"),
    FORBIDDEN("FORBIDDEN"),
    CONFLICT("CONFLICT"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    INVALID_REQUEST_BODY("INVALID_REQUEST_BODY"),
    MISSING_PARAMETER("MISSING_PARAMETER"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    INTERNAL_ERROR("INTERNAL_ERROR"),

    // Phase
    INVALID_PHASE_TRANSITION("INVALID_PHASE_TRANSITION"),

    // Board
    BOARD_NOT_FOUND("BOARD_NOT_FOUND"),

    // Card
    CARD_NOT_FOUND("CARD_NOT_FOUND"),
    CARD_NOT_EDITABLE("CARD_NOT_EDITABLE"),

    // Vote
    VOTE_LIMIT_REACHED("VOTE_LIMIT_REACHED"),
    DUPLICATE_VOTE("DUPLICATE_VOTE"),

    // Participant
    PARTICIPANT_NOT_FOUND("PARTICIPANT_NOT_FOUND"),
    NOT_FACILITATOR("NOT_FACILITATOR"),
}
